### PR TITLE
update

### PR DESCRIPTION
**Pull request by robfordww**
updated the deprecated ioutil package.  webrpc requires go v1.16, which is the same version where ioutil was deprecated.

### CODE REVIEW

**Comment by VojtechVitek** [comment]
@robfordww Can you rebase please?

**Comment by robfordww** [comment]
rebased, but I see the one test fail; but that is perhaps expected for this change?

**Comment by VojtechVitek** [comment]
Hi Rob,

no, these are not expected changes.

The `./_examples/**/*.gen.go` files are code-generated by https://github.com/webrpc/gen-golang. You'd have to submit a PR there too, so we could merge this.

**Comment by VojtechVitek** [comment]
@robfordww could you please open a new PR with no changes to the `_examples/` folder?

**Comment by VojtechVitek** [comment]
`ioutil` removal finished in latest golang@v0.13.0.

**Pull request closed without merging**
