### PR TITLE
[WIP] Implement Go language schema parser: webrpc-gen -schema=contract.go

### PR DESCRIPTION
**Pull request by VojtechVitek**
Goal: Allow WebRPC to parse schema from a Go source file instead of RIDL/JSON.

I'm seeking early feedback on this from @pkieltyka. I'll start adding test cases and examples in the upcoming days.

Based on work at https://github.com/vcilabs/webrpc/pull/2

### CODE REVIEW

**Comment by pkieltyka** [comment]
Neat — do you have an example schema written for this format? Also, why not use RIDL or JSON.. what’s the benefits of Go for schema language?

**Comment by VojtechVitek** [comment]
A typical contract would look exactly like what is currently being generated by webrpc-gen (`-target=go`) in the `// types` section. Example:

```go
package contract

type Book struct {
  ID   int    `db:"id,pk" json:"id"`
  Name string `db:"name" json:"name"`
}

type Library interface {
  GetBooks(context.Context) ([]*Book, error)
  GetBook(context.Context, bookID int) (*Book, error)
  BorrowBook(context.Context, bookID int) error
}
```

I'll provide some more examples and tests next week.

The benefit is that you don't need to learn or maintain contract in (yet another) schema language. RIDL is **much** easier to learn and more flexible than Protobuf, kudos for that. But what if we could simply use Go code instead?

**Comment by pkieltyka** [comment]
That looks nice too and I agree it’s not to have familiar Go code.. but.. webrpc isn’t a Go framework, it’s language agnostic

**Comment by pkieltyka** [comment]
I’ll one day support webrpc for rust as well, and we already support for node, and will add more languages

**Comment by pkieltyka** [comment]
However, I do think your parser is cool to have .. ideally the webrpc/schema package stays small, as it is, and all code generators are built against it, then we could have webrpc/ org where we could have other parsers and companion packages, which use webrpc/schema

I’ve been planning for a while to modularize the packages of webrpc so it’s a schema, and even code generators would be outside of the core, so it’s easier for third parities to use it

**Comment by VojtechVitek** [comment]
Nice, I like that plan. Do you want me to keep going, for visibility? Or should I create a separate repo right away, since we're not likely to merge this into the core?

I'm also planning to write a generator for Swagger docs one day.

**Comment by pkieltyka** [comment]
We can make a separate repo in webrpc org if you like — but ya I plan to make this repo smaller so won’t merge here

**Comment by VojtechVitek** [comment]
Sounds good. Pls, let me know when you're ready to accept 3rd party parsers/generators :)

WebRPC is yet another briliant project, @pkieltyka. Well done! ❤️ 

For anyone else interested, I'll keep going at https://github.com/golang-cz/webrpc for now.

**Pull request closed without merging**
