### PR TITLE
additional generator functions

### PR DESCRIPTION
**Pull request by austinmilt**
This PR adds generator functions to assist in code generation. Specifically

- all of sprig v3 (https://github.com/Masterminds/sprig/tree/v3.2.3) as suggested by @VojtechVitek 
- `lastIndex` was added to assist in branching logic on the last iteration of a `range`

### CODE REVIEW

**Comment by austinmilt** [comment]
@VojtechVitek I did not add version numbers in `gen/funcmap.go` or changes in `CHANGELOG.md` as I'm unfamiliar with how you are maintaining them. Feel free to tell me what to change or update yourself 🤝

**Comment by VojtechVitek** [comment]
@austinmilt you can use `v0.18.0`.

I was thinking we could import all template functions from https://github.com/Masterminds/sprig v3, which is used by Helm and Hugo. They have the math func equivalent -- `add`, `sub`, `div`, `mul`.

Could you also document the new functions at https://github.com/webrpc/webrpc/tree/master/gen#webrpc-gen-functions ?

**Comment by austinmilt** [comment]
> @austinmilt you can use `v0.18.0`.
> 
> I was thinking we could import all template functions from https://github.com/Masterminds/sprig v3, which is used by Helm and Hugo. They have the math func equivalent -- `add`, `sub`, `div`, `mul`.
> 
> Could you also document the new functions at https://github.com/webrpc/webrpc/tree/master/gen#webrpc-gen-functions ?

I will replace my duplicate methods with the equivalent from `sprig`. I see there are some other duplicates (e.g. `ternary`) that I did not add that I dont want to touch in this PR.

**Review by VojtechVitek — APPROVED** [review]
LGTM

**Comment by VojtechVitek** [comment]
Very cool addition. Thank you @austinmilt

**Pull request merged**
