### PR TITLE
get all required fields

### PR DESCRIPTION
**Pull request by LukasJenicek**

### CODE REVIEW

**Review by VojtechVitek — APPROVED** [review]
LGTM

**Comment by pkieltyka** [comment]
LGTM too -- what will we use this for btw?

**Comment by LukasJenicek** [comment]
@pkieltyka here: https://github.com/webrpc/gen-openapi/pull/14

I need to get if at least one field is required, because `required` attribute without any fields was causing `redocly` to fail render the openapi document.

**Comment by pkieltyka** [comment]
nice :) I thought so.. lets merge it as you're ready

**Pull request merged**
